#!/usr/bin/bash

# Define command-line argument


if [ $# -lt 3 ]; then
	echo "use next args: top pod argocd (or demo) "
  exit
fi

# The first ARG is KUBECOMMAND, for example "top"

KUBECOMMAND=$1

# The second ARG is RESOURCE_TYPE, for example "node" or "pod"

RESOURCE_TYPE=$2

# The third ARG is NAMESPACE, for example argocd

NAMESPACE=$3

# Retrieve resource usage statistics from Kubernetes

kubectl "$KUBECOMMAND" "$RESOURCE_TYPE" "-n" "$NAMESPACE"  | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  
echo "${RESOURCE_TYPE}  ${NAMESPACE}  ${NAME}  ${CPU}  ${MEMORY}" | tee output.txt
done
