#!/usr/bin/bash

# Define command-line arguments

# arg1 - command, for example "top"

arg1=$1

# arg2 - target "node" or "pod"

arg2=$2

Namespace=$(kubectl get namespaces)

# Retrieve resource usage statistics from Kubernetes
kubectl arg1 arg2 | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $4}')

  # Output the statistics to the console
echo "${arg2}, ${Namespace}, ${NAME}, ${CPU}, ${MEMORY}"
done
